[project]
name = "text2sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.0",
    "python-dotenv>=1.1.1",
    "smolagents>=1.20.0",
    "sqlalchemy>=2.0.41",
]
